#! /usr/bin/env bash
env_file=$(basename `mktemp`)
out_file=$(basename `mktemp`)
cch_dir=$(basename `mktemp`)

_oldPWD="$PWD"
osname=openbsd

rsyncToVM() {
  _pwd="$PWD"
  cd "$_oldPWD"
  rsync -avrtopg -e 'ssh -o MACs=umac-64-etm@openssh.com' --exclude _actions --exclude _PipelineMapping  $HOME/work/  $osname:work
  cd "$_pwd"
}

rsyncBackFromVM() {
  _pwd="$PWD"
  cd "$_oldPWD"
  rsync -vrtopg -e 'ssh -o MACs=umac-64-etm@openssh.com' $osname:work/ $HOME/work
  cd "$_pwd"
}

ssh -T openbsd <<EOF
  touch "/tmp/${env_file}" "/tmp/${out_file}"
EOF

# copy files to VM
echo "::group::Copy workspace to VM"
rsyncToVM
echo "::endgroup::"

# GITHUB_* is automatically forwarded, as is LC_* (!)
ssh -T -o SendEnv=NOT_CRAN -o SendEnv=CI -o SendEnv=R_LIBS_USER openbsd \
  "cd $GITHUB_WORKSPACE ; " \
  GITHUB_ENV="/tmp/${env_file}" GITHUB_OUTPUT="/tmp/${out_file}" \
  R_PKG_CACHE_DIR="/tmp/${cch_dir}" XDG_CACHE_HOME="/tmp/${cch_dir}" \
  R_LIB_FOR_PAK=/usr/local/lib/R/site-library \
  sh -l -c '"R --no-save -q"' < $1
status=$?

# copy files back from VM
echo "::group::Copy workspace from from VM"
rsyncBackFromVM
echo "::endgroup::"

scp openbsd:/tmp/${env_file} /tmp/${env_file} || true
scp openbsd:/tmp/${out_file} /tmp/${out_file} || true
touch /tmp/${env_file} /tmp/${out_file}
cat /tmp/${env_file} >> $GITHUB_ENV
cat /tmp/${out_file} >> $GITHUB_OUTPUT

if [ "$status" != "0" ]; then
  echo "::error ::Command failed."
fi

exit $status
