#! /usr/bin/env bash
env_file=$(basename `mktemp`)
out_file=$(basename `mktemp`)
cch_dir=$(basename `mktemp`)

ssh -T netbsd <<EOF
  touch "/tmp/${env_file}" "/tmp/${out_file}"
EOF

# copy files to VM
echo "::group::Copy workspace to VM"
bash /home/runner/work/_actions/vmactions/netbsd-vm/v1/run.sh rsyncToVM
echo "::endgroup::"

# GITHUB_* is automatically forwarded, as is LC_* (!)
ssh -T -o SendEnv=NOT_CRAN -o SendEnv=CI -o SendEnv=R_LIBS_USER netbsd \
  "cd $GITHUB_WORKSPACE ; " \
  GITHUB_ENV="/tmp/${env_file}" GITHUB_OUTPUT="/tmp/${out_file}" \
  R_PKG_CACHE_DIR="/tmp/${cch_dir}" XDG_CACHE_HOME="/tmp/${cch_dir}" \
  R_LIB_FOR_PAK=/usr/pkg/lib/R/site-library LANG=en_US.UTF-8 LC_CTYPE=C LC_COLLATE=C MAKE=gmake \
  PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/pkg/sbin:/usr/pkg/bin:/usr/games:/usr/X11R7/bin:/usr/local/sbin:/usr/local/bin \
  R --no-save -q < $1
status=$?

# copy files back from VM
echo "::group::Copy workspace from from VM"
bash /home/runner/work/_actions/vmactions/netbsd-vm/v1/run.sh rsyncBackFromVM
echo "::endgroup::"

scp netbsd:/tmp/${env_file} /tmp/${env_file} || true
scp netbsd:/tmp/${out_file} /tmp/${out_file} || true
touch /tmp/${env_file} /tmp/${out_file}
cat /tmp/${env_file} >> $GITHUB_ENV
cat /tmp/${out_file} >> $GITHUB_OUTPUT

if [ "$status" != "0" ]; then
  echo "::error ::Command failed."
fi

exit $status
