on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

name: freebsd.yaml

jobs:
  freebsd:
    runs-on: ubuntu-latest
    name: FreeBSD ${{ matrix.release }}
    strategy:
      fail-fast: false
      matrix:
        release:
        - '15.1'
        - '14.5'
        - '13.5'
    steps:
      - uses: actions/checkout@v7
      - uses: r-hub/actions/setup-r-freebsd@v1
        with:
          release: ${{ matrix.release }}
      - uses: r-hub/actions/platform-info@v1

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: none
          install-pandoc: false
          install-quarto: false
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
          upload-snapshots: true
