#! /usr/bin/env bash
env_file=$(basename `mktemp`)
out_file=$(basename `mktemp`)
cch_dir=$(basename `mktemp`)

ssh freebsd <<EOF
  touch "/tmp/${env_file}" "/tmp/${out_file}"
EOF

# GITHUB_* is automatically forwarded, as is LC_* (!)
ssh -o SendEnv=NOT_CRAN -o SendEnv=CI freebsd \
  GITHUB_ENV="/tmp/${env_file}" GITHUB_OUTPUT="/tmp/${out_file}" \
  R_PKG_CACHE_DIR="/tmp/${cch_dir}" XDG_CACHE_HOME="/tmp/${cch_dir}" \
  R --no-save -q < $1
status=$?

scp freebad:/tmp/${env_file} /tmp/${env_file} || true
scp freebsd:/tmp/${out_file} /tmp/${out_file} || true
touch /tmp/${env_file} /tmp/${out_file}
cat /tmp/${env_file} >> $GITHUB_ENV
cat /tmp/${out_file} >> $GITHUB_OUTPUT

if [ "$status" != "0" ]; then
  echo "::error ::Command failed."
fi

exit $status
