name: Setup macOS system packages

on:
  workflow_dispatch:
    inputs:
      package:
        description: |
          R package to test.
        default: tiff

jobs:
  test:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: macos-latest }
          - { os: macos-15-intel }

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./setup-r-sysreqs
      - uses: r-lib/actions/setup-r@f9a764fea8d5c63df6ef9a5c7795bf7deb5d7e05 # v2.14.0
      - name: Compiling R package
        run: |
          R -e 'options(warn = 2); install.packages("${{ github.event.inputs.package }}", repos = "https://cran.rstudio.com", type = "source")'
        shell: bash
